### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by BookOwl** [tjvr/nefarious#1]
First, I want to say that this look like a really cool project.

I tried to finish the example that you gave in the README:
```
define Int:a + Int:b { return (INT_ADD a b) }
define Int:a - Int:b { return (INT_SUB a b) }
define Int:a < Int:b { return (INT_LT a b) }
define if Bool:test then Block:tv else Block:fv { return (IF_THEN_ELSE test tv fv) }

define fib Int:n {
    if n < 2 then { return 1 } else { return fib (n - 1) + fib (n - 2) }
}
```
However, when I try to run it with `./nfs --parse fib.nfs`, I get an error:
```
RPython traceback:
  File "nefarious___init__.c", line 159, in entry_point
  File "nefarious___init__.c", line 364, in run
  File "nefarious_grammar.c", line 1363, in parse
  File "nefarious_parser.c", line 2483, in grammar_parse
  File "nefarious_parser.c", line 4774, in Column_eval_exit
  File "nefarious_grammar.c", line 1915, in DefineMacro_exit
Fatal RPython error: AssertionError
Abort trap: 6
```
I'm assuming that this means I did something wrong. What should I do to get this to work?

Also, how do I define the entry point of the program?

**Comment by tjvr** [comment]
The precise error in this case is that the typechecker is very stupid. Your function doesn't end with an expression, so it can't infer the type of the function! Try omitting `return` to fix this. If you run the interpreter on top of Python -- eg. `pypy -m nefarious fib.nfs` -- the error might be clearer.

More broadly I'm suspicious about trying to define `if` inside the language. Note that unevaluated inputs aren't yet implemented, so you can't say eg. "define while (Uneval Bool):test"...

The entry point? Just write commands at the root level :-)

The readme is quite out of date, you might be better off looking at some of the newer examples (e.g. in `bench/`).

A working version might look like this:

```
defprim Int:a + Int:b { INT_ADD a b }
defprim Int:a - Int:b { INT_SUB a b }
defprim Int:a < Int:b { INT_LT a b }
defprim if Bool:test then Block:tv else Block:fv {
  IF_THEN_ELSE test tv fv
}


define fib Int:n {
    if n < 2 then { return 1 } else { return fib (n - 1) + fib (n - 2) }
}

fib 5
```

**Comment by tjvr** [comment]
I'm glad you like my project! But I should probably make clear that this is in no way intended for serious use. The parser in particular is very experimental, and there are lots of weird edge cases. Operator precedence doesn't work properly. There are basically no helpful error messages whatsoever (as you've discovered!).

At the moment I'm just making it run really fast, since the goal of my third-year undergrad project is to make a fast VM for nefarious. :-)

**Comment by BookOwl** [comment]
OK, thanks.

**Comment by BookOwl** [comment]
> But I should probably make clear that this is in no way intended for serious use

I wasn't thinking that this was, I just love experimenting with this kind of stuff.

**Comment by tjvr** [comment]
> I wasn't thinking that this was, I just love experimenting with this kind of stuff.

Glad to hear it! :) Let me know if you run into anything else..
